import 'package:flutter/material.dart';
import 'package:go_router/go_router.dart';
import 'package:provider/provider.dart';
import 'package:tes_gradle/features/domain/entities/berita.dart';
import 'package:tes_gradle/features/presentation/provider/berita_provider.dart';
import 'package:tes_gradle/features/presentation/router/approutes.dart';
import 'package:tes_gradle/features/presentation/style/color.dart';
import 'package:tes_gradle/features/presentation/style/typography.dart';
import 'package:file_picker/file_picker.dart';
import 'package:http/http.dart' as http;
import 'dart:convert';
import 'package:http_parser/http_parser.dart';

class BeritaAdminScreen extends StatefulWidget {
  const BeritaAdminScreen({super.key});

  @override
  _BeritaAdminScreenState createState() => _BeritaAdminScreenState();
}

class _BeritaAdminScreenState extends State<BeritaAdminScreen> {
  final _formKey = GlobalKey<FormState>();
  final TextEditingController _judulController = TextEditingController();
  final TextEditingController _deskripsiController = TextEditingController();
  String? _uploadedImageUrl;
  bool _isUploading = false;

  Future<String> uploadImage(String filePath) async {
    final url = Uri.parse('https://api.cloudinary.com/v1_1/dpbw0ztwl/upload');
    final request =
        http.MultipartRequest('POST', url)
          ..fields['upload_preset'] = 'a5tgii2s'
          ..files.add(
            await http.MultipartFile.fromPath(
              'file',
              filePath,
              contentType: MediaType('image', 'jpeg'),
            ),
          );

    final response = await request.send();
    if (response.statusCode == 200) {
      final responseData = await response.stream.toBytes();
      final responseString = String.fromCharCodes(responseData);
      final jsonMap = jsonDecode(responseString);
      return jsonMap['secure_url'];
    } else {
      throw Exception('Failed to upload image');
    }
  }

  Future<void> _uploadPhoto() async {
    setState(() {
      _isUploading = true;
    });

    try {
      final result = await FilePicker.platform.pickFiles(type: FileType.image);
      if (result != null && result.files.single.path != null) {
        final filePath = result.files.single.path!;
        final uploadedUrl = await uploadImage(filePath);
        setState(() {
          _uploadedImageUrl = uploadedUrl; // URL gambar dari Cloudinary
        });
      }
    } catch (e) {
      print('Error uploading photo: $e');
    } finally {
      setState(() {
        _isUploading = false;
      });
    }
  }

  Future<void> _addBerita() async {
    if (_judulController.text.isEmpty ||
        _deskripsiController.text.isEmpty ||
        _uploadedImageUrl == null) {
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(
          content: Text('Please fill all fields and upload an image'),
        ),
      );
      return;
    }

    final beritaProvider = Provider.of<BeritaProvider>(context, listen: false);
    final newBerita = Berita(
      id: '', // ID will be generated by Firestore
      gambar: _uploadedImageUrl!, // URL gambar dari Cloudinary
      judul: _judulController.text,
      isi: _deskripsiController.text,
    );
    await beritaProvider.addBerita(newBerita);

    _judulController.clear();
    _deskripsiController.clear();
    setState(() {
      _uploadedImageUrl = null;
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: PreferredSize(
        preferredSize: Size.fromHeight(60.0),
        child: AppBar(
          flexibleSpace: Container(
            decoration: BoxDecoration(
              image: DecorationImage(
                image: AssetImage('assets/images/top bar.png'),
                fit: BoxFit.cover,
              ),
            ),
          ),
          title: Text(
            'Tambah Berita',
            style: AppTextStyles.heading_3_medium.copyWith(
              color: AppColors.c020608,
            ),
          ),
          backgroundColor: Colors.transparent,
          leading: IconButton(
            icon: Icon(Icons.arrow_back, color: AppColors.c020608),
            onPressed: () {
              context.go(AppRoutes.admin);
            },
          ),
        ),
      ),
      body: Padding(
        padding: const EdgeInsets.all(16.0),
        child: Column(
          children: [
            Form(
              key: _formKey,
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  Text(
                    'Tambah Berita Baru',
                    style: AppTextStyles.heading_4_bold.copyWith(
                      color: AppColors.c2a6892,
                    ),
                  ),
                  const SizedBox(height: 16),
                  TextFormField(
                    controller: _judulController,
                    decoration: const InputDecoration(
                      labelText: 'Judul Berita',
                      border: OutlineInputBorder(),
                    ),
                    validator: (value) {
                      if (value == null || value.isEmpty) {
                        return 'Judul tidak boleh kosong';
                      }
                      return null;
                    },
                  ),
                  const SizedBox(height: 16),
                  TextFormField(
                    controller: _deskripsiController,
                    decoration: const InputDecoration(
                      labelText: 'Deskripsi Berita',
                      border: OutlineInputBorder(),
                    ),
                    maxLines: 5,
                    validator: (value) {
                      if (value == null || value.isEmpty) {
                        return 'Deskripsi berita tidak boleh kosong';
                      }
                      return null;
                    },
                  ),
                  const SizedBox(height: 16),
                  ElevatedButton(
                    onPressed: _uploadPhoto,
                    child: const Text('Upload Gambar'),
                  ),
                  const SizedBox(height: 8),
                  if (_isUploading) const CircularProgressIndicator(),
                  if (_uploadedImageUrl != null)
                    Image.network(
                      _uploadedImageUrl!,
                      height: 150,
                      width: double.infinity,
                      fit: BoxFit.cover,
                    ),
                  const SizedBox(height: 16),
                  ElevatedButton(
                    onPressed: _addBerita,
                    style: ElevatedButton.styleFrom(
                      backgroundColor: AppColors.c2a6892,
                      padding: const EdgeInsets.symmetric(
                        horizontal: 40,
                        vertical: 12,
                      ),
                      shape: RoundedRectangleBorder(
                        borderRadius: BorderRadius.circular(8.0),
                      ),
                    ),
                    child: const Text(
                      'Tambah Berita',
                      style: TextStyle(color: Colors.white),
                    ),
                  ),
                ],
              ),
            ),
            const SizedBox(height: 32),
            Expanded(
              child: Consumer<BeritaProvider>(
                builder: (context, beritaProvider, child) {
                  if (beritaProvider.isLoading) {
                    return const Center(child: CircularProgressIndicator());
                  }
                  final beritaList = beritaProvider.beritaList ?? [];
                  return ListView.builder(
                    itemCount: beritaList.length,
                    itemBuilder: (context, index) {
                      final berita = beritaList[index];
                      return Card(
                        margin: const EdgeInsets.symmetric(vertical: 8.0),
                        child: ListTile(
                          leading: Image.network(
                            berita.gambar,
                            width: 50,
                            height: 50,
                            fit: BoxFit.cover,
                            errorBuilder: (context, error, stackTrace) {
                              return const Icon(Icons.broken_image);
                            },
                          ),
                          title: Text(berita.judul),
                          subtitle: Text(
                            berita.isi,
                            maxLines: 2,
                            overflow: TextOverflow.ellipsis,
                          ),
                          trailing: IconButton(
                            icon: const Icon(Icons.delete, color: Colors.red),
                            onPressed: () async {
                              await beritaProvider.removeBerita(berita.id);
                              ScaffoldMessenger.of(context).showSnackBar(
                                const SnackBar(
                                  content: Text('Berita berhasil dihapus!'),
                                ),
                              );
                            },
                          ),
                        ),
                      );
                    },
                  );
                },
              ),
            ),
          ],
        ),
      ),
    );
  }
}
